/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
  'excerpt' : string,
  'category' : string,
}
export interface Cuisine {
  'region' : string,
  'name' : string,
  'description' : string,
  'featuredDishes' : Array<string>,
}
export interface Recipe {
  'title' : string,
  'instructions' : Array<string>,
  'imageUrl' : string,
  'cuisine' : string,
  'prepTime' : string,
  'servings' : bigint,
  'ingredients' : Array<string>,
}
export interface Submission {
  'title' : string,
  'content' : string,
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'submissionType' : SubmissionType,
}
export type SubmissionType = { 'story' : null } |
  { 'recipe' : null };
export interface _SERVICE {
  'addArticle' : ActorMethod<[Article], undefined>,
  'addCuisine' : ActorMethod<[Cuisine], undefined>,
  'addRecipe' : ActorMethod<[Recipe], undefined>,
  'filterRecipesByCuisine' : ActorMethod<[string], Array<Recipe>>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllCuisines' : ActorMethod<[], Array<Cuisine>>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getArticle' : ActorMethod<[string], Article>,
  'getCuisine' : ActorMethod<[string], Cuisine>,
  'getRecipe' : ActorMethod<[string], Recipe>,
  'getUserSubmissions' : ActorMethod<[Principal], Array<Submission>>,
  'searchRecipes' : ActorMethod<[string], Array<Recipe>>,
  'submitContent' : ActorMethod<[Submission], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];