/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Recipe {
    title: string;
    instructions: Array<string>;
    imageUrl: string;
    cuisine: string;
    prepTime: string;
    servings: bigint;
    ingredients: Array<string>;
}
export interface Submission {
    title: string;
    content: string;
    name: string;
    email: string;
    timestamp: bigint;
    submissionType: SubmissionType;
}
export interface Cuisine {
    region: string;
    name: string;
    description: string;
    featuredDishes: Array<string>;
}
export interface Article {
    title: string;
    content: string;
    author: string;
    timestamp: bigint;
    excerpt: string;
    category: string;
}
export enum SubmissionType {
    story = "story",
    recipe = "recipe"
}
export interface backendInterface {
    addArticle(article: Article): Promise<void>;
    addCuisine(cuisine: Cuisine): Promise<void>;
    addRecipe(recipe: Recipe): Promise<void>;
    filterRecipesByCuisine(cuisine: string): Promise<Array<Recipe>>;
    getAllArticles(): Promise<Array<Article>>;
    getAllCuisines(): Promise<Array<Cuisine>>;
    getAllRecipes(): Promise<Array<Recipe>>;
    getArticle(title: string): Promise<Article>;
    getCuisine(name: string): Promise<Cuisine>;
    getRecipe(title: string): Promise<Recipe>;
    getUserSubmissions(user: Principal): Promise<Array<Submission>>;
    searchRecipes(searchText: string): Promise<Array<Recipe>>;
    submitContent(submission: Submission): Promise<void>;
}
import type { Submission as _Submission, SubmissionType as _SubmissionType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addArticle(arg0: Article): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArticle(arg0);
            return result;
        }
    }
    async addCuisine(arg0: Cuisine): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCuisine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCuisine(arg0);
            return result;
        }
    }
    async addRecipe(arg0: Recipe): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecipe(arg0);
            return result;
        }
    }
    async filterRecipesByCuisine(arg0: string): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterRecipesByCuisine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterRecipesByCuisine(arg0);
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return result;
        }
    }
    async getAllCuisines(): Promise<Array<Cuisine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCuisines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCuisines();
            return result;
        }
    }
    async getAllRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipes();
            return result;
        }
    }
    async getArticle(arg0: string): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return result;
        }
    }
    async getCuisine(arg0: string): Promise<Cuisine> {
        if (this.processError) {
            try {
                const result = await this.actor.getCuisine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCuisine(arg0);
            return result;
        }
    }
    async getRecipe(arg0: string): Promise<Recipe> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return result;
        }
    }
    async getUserSubmissions(arg0: Principal): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubmissions(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubmissions(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchRecipes(arg0: string): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRecipes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRecipes(arg0);
            return result;
        }
    }
    async submitContent(arg0: Submission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContent(to_candid_Submission_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContent(to_candid_Submission_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_SubmissionType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionType): SubmissionType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    name: string;
    email: string;
    timestamp: bigint;
    submissionType: _SubmissionType;
}): {
    title: string;
    content: string;
    name: string;
    email: string;
    timestamp: bigint;
    submissionType: SubmissionType;
} {
    return {
        title: value.title,
        content: value.content,
        name: value.name,
        email: value.email,
        timestamp: value.timestamp,
        submissionType: from_candid_SubmissionType_n4(_uploadFile, _downloadFile, value.submissionType)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    story: null;
} | {
    recipe: null;
}): SubmissionType {
    return "story" in value ? SubmissionType.story : "recipe" in value ? SubmissionType.recipe : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n2(_uploadFile, _downloadFile, x));
}
function to_candid_SubmissionType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): _SubmissionType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Submission_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Submission): _Submission {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    name: string;
    email: string;
    timestamp: bigint;
    submissionType: SubmissionType;
}): {
    title: string;
    content: string;
    name: string;
    email: string;
    timestamp: bigint;
    submissionType: _SubmissionType;
} {
    return {
        title: value.title,
        content: value.content,
        name: value.name,
        email: value.email,
        timestamp: value.timestamp,
        submissionType: to_candid_SubmissionType_n8(_uploadFile, _downloadFile, value.submissionType)
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): {
    story: null;
} | {
    recipe: null;
} {
    return value == SubmissionType.story ? {
        story: null
    } : value == SubmissionType.recipe ? {
        recipe: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
